---
title: "Statistical Project_2640948k"
author: "Hoi Him Kwok (2640948k)"
date: "06/10/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

# Introductaion

## Background

It is well known that sport is essential for individual's physical health. With sport, we can train our muscles and respiratory, as well as enhancing immunity (Ornulf Seippel. 2006). Urbanizes, however, do lack of exercise due to various reasons. such as job character and long working period. In this way, the risk of obesity, depression, high blood pressures, as well as a series of cardiovascular diseases increased rapidly, being harmful to public health. For solving health issues, augmented reality (AR) videos games are in consideration. Augmented reality is an extended version of VR. It combines virtual elements with real world, through the assist of visual devices, including eyeglasses, monitor, as well as smart devices (Tim Fisher. 2021). Overlapping on and tracking in real world objects, AR objects seems occupying the same space. Besides visualization, AR system can also contain sound and tactile, for providing an new form of world. AR technology can be applied in various types of applications, such as map and games. In this study, we focus on Pokemon Go, a popular AR mobile games.

Pokemon Go is a famous mobile game developed by Niantic Inc, as well as released at 2016 on both Apple Store and Google Play (Luke Reilly. 2017). Pokemon Go players using GPS signals to locate, catch (also obtain ingredients for training Pokemon), hatch (players walk around 2 to 10 km to obtain a Pokemon) and train virtual creatures, Pokemon. Those Pokemon can be used for battling and Gym controlling (Andrew Webster. 2015). Pokemon Go use a map and camera to display the virtual spots, like Pokestop, Gym and activity location points. (Smith 2017) Pokemon Go is a celebrated application, with 632 millions times of downloading and 147 millions of monthly active players. Due to the popularity, Pokemon Go plausibly facilitating an obvious behavior change in public health (Dillet. 2016).

According to multiple researches, Pokemon Go obviously and positively affect the amount of physical activities.  We find that Pokémon Go leads to significant increases in physical activity over a period of 30 days, with particularly engaged users (ie, those making multiple search queries for details about game usage) increasing their activity by 1473 steps a day on average, a more than 25% increase compared with their prior activity level (P<.001). In the short time span of the study, we estimate that Pokémon Go has added a total of 144 billion steps to US physical activity. Furthermore, Pokémon Go has been able to increase physical activity across men and women of all ages, weight status, and prior activity levels showing this form of game leads to increases in physical activity with significant implications for public health. In particular, we find that Pokémon Go is able to reach low activity populations, whereas all 4 leading mobile health apps studied in this work largely draw from an already very active population. (Gunther Eysenbach. 2016)

## Research Objectives



# Methodology

## Data Description


## Model Selection



# Analysis Result



# Discussion and Conclusion





# Reference

https://www.ign.com/articles/2015/09/10/pokemon-go-coming-to-smartphones

https://www.theverge.com/2015/9/10/9300101/pokemon-go-nintendo-mobile-games

https://www.tandfonline.com/doi/full/10.1080/17430430500355790?scroll=top&needAccess=true

https://www.lifewire.com/augmented-reality-ar-definition-4155104

Smith, C. (2017, November 12).80 amazing Pokemon Go statistics. RetrievedNovember 17, 2017, from https://expandedramblings.com/index.php/pokemon-go-statistics/.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5174727/